/*
 * Cáceres Ramos, Fredy Antonio
 * CR11005
 * 2016/09/26 11:52 p.m.
 * Fundamentos de Base de Datos
 * Guía 2 - DDL & DML
 */

  USE master
  SELECT * FROM INFORMATION_SCHEMA.TABLES
  SELECT * FROM SYSOBJECTS
  SELECT * FROM SYSOBJECTS WHERE NAME = 'ADDRESS'
  SELECT TABLE_NAME FROM  INFORMATION_SCHEMA.TABLES