/*
 * Cáceres Ramos, Fredy Antonio
 * CR11005
 * 2016/09/27 12:01 a.m.
 * Fundamentos de Base de Datos
 * Guía 2 - DDL & DML
 */

 CREATE DATABASE PRUEBA
 GO

 USE PRUEBA
 CREATE TABLE ALUMNO (
	DUE CHAR(7) PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(25),
	APELLIDOS VARCHAR(25))

 ALTER TABLE ALUMNO ADD CARRERA VARCHAR(25) 

 CREATE TABLE MATERIA (
	CÓDIGO CHAR(7) NOT NULL,
	NOMBRE VARCHAR(25) NOT NULL,
	APELLIDOS VARCHAR(25))

 ALTER TABLE MATERIA ADD PRIMARY KEY(CÓDIGO)

 ALTER TABLE ALUMNO DROP COLUMN CARRERA		-- Elimina una columna de una tabla
 DROP TABLE  ALUMNO							-- Elimina la tabla completa, drop elimina objetos

 ALTER TABLE ALUMNO ADD MATERIA CHAR(7)

 ALTER TABLE ALUMNO ADD CONSTRAINT fk_AlumnoMateria
 FOREIGN KEY (MATERIA)
 REFERENCES MATERIA(CÓDIGO)